### ISSUE TITLE
Compatibility with sklearn model_selection module

### ISSUE THREAD

**Issue by mnarayan** [skggm/skggm#90]
Older cross validation module has been deprecated 

```
DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection 
module into which all the refactored classes and functions are moved. Also note that the interface of
the new CV iterators are different from that of this module. This module will be removed in 0.20.
```

It might make sense to make all our model selection variants (EBIC, CV, and more to come) compatible with new interface.

**Comment by jasonlaska** [comment]
This is already addressed, please pull latest develop branch

**Comment by jasonlaska** [comment]
Abd close the ticket

**Comment by mnarayan** [comment]
I still get the warnings however. I'm using latest develop branch.

**Comment by jasonlaska** [comment]
Did you reinstall requirements

**Comment by mnarayan** [comment]
Closing this issue as I don't get the warnings anymore.
